version: '3.6'

services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: user
      POSTGRES_DB: personaltaskdb
  
volumes:  
  postgres: 