// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskManagement.Infra.EF.Contexts;

#nullable disable

namespace TaskManagement.PostgreSql.Migrations
{
    [DbContext(typeof(TaskManagementEFContext))]
    partial class TaskManagementEFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("TaskManagement")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskManagement.Domain.Entities.PersonalTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDay")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("StartDay")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("PersonalTask", "TaskManagement");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9aa4c4f-3077-4276-867c-59fba7959d19"),
                            CreateDate = new DateTime(2024, 5, 14, 0, 44, 41, 618, DateTimeKind.Local).AddTicks(2750),
                            Description = "Set kick-off meeting",
                            StartDay = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = 1,
                            Title = "Set kick-off meeting"
                        },
                        new
                        {
                            Id = new Guid("ac2be6ff-0c80-4d51-8624-f9c97a0abb4b"),
                            CreateDate = new DateTime(2024, 5, 14, 0, 44, 41, 618, DateTimeKind.Local).AddTicks(2780),
                            Description = "Final resource plan",
                            StartDay = new DateTime(2024, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = 2,
                            Title = "Final resource plan"
                        },
                        new
                        {
                            Id = new Guid("70bbcb75-affb-4c85-999a-77aea00ed55a"),
                            CreateDate = new DateTime(2024, 5, 14, 0, 44, 41, 618, DateTimeKind.Local).AddTicks(2780),
                            Description = "Api development",
                            StartDay = new DateTime(2024, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = 3,
                            Title = "Api development"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
